### ISSUE TITLE
webpack preload插件如果preload了异步js模块在html里面貌似没有被替换掉

### ISSUE THREAD

**Issue by zcmk123** [toxic-johann/webpack-cdn-upload-plugin#58]
如题。。我又回来了。。。

**Comment by toxic-johann** [comment]
没太用过这个插件。能提供下相关的可复现代码吗。

**Comment by zcmk123** [comment]
啊。。就是你简介里面说的preload-webpack-plugin 这个插件，周末我回去看看能不能整个代码出来

**Comment by toxic-johann** [comment]
哦。好的。

**Comment by toxic-johann** [comment]
啊。。。原来这个插件我也贡献过。。。时间太久都忘了。。

**Comment by toxic-johann** [comment]
我大概知道为什么没替换了

**Comment by zcmk123** [comment]
> 我大概知道为什么没替换了

那麻烦大佬了

**Comment by toxic-johann** [comment]
发布了最新版本 https://www.npmjs.com/package/webpack-cdn-upload-plugin/v/2.2.1 可以看看能否修复需求。

**Comment by zcmk123** [comment]
> 发布了最新版本 https://www.npmjs.com/package/webpack-cdn-upload-plugin/v/2.2.1 可以看看能否修复需求。

好滴我试试

**Comment by zcmk123** [comment]
> 发布了最新版本 https://www.npmjs.com/package/webpack-cdn-upload-plugin/v/2.2.1 可以看看能否修复需求。

阔以了，感谢
